
#配置数据源的属性
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/bills?useUnicode=true&useSSL=false&characterEncoding=utf8
      username: root
      password: 123456
      max-active: 20
      max-wait: 5000
      initial-size: 1
      filters: stat,log4j,wall
      validation-query: SELECT 'X'  #验证连接
      enable: true

  devtools:
    restart:
      enabled: true  #页面开启热部署

  #监控配置
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 123456
        url-pattern: /druid/*


  #thymeleaf的配置
  thymeleaf:
    cache: false
    enabled: true
#      web-stat-filter:
#        enabled: true
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css.*.ico,/druid/*"

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


#mybatisplus的配置
mybatis-plus:
  mapper-locations:
  -classpath: mapper/*Mapper.xml
  global-config:
    gb-config:
      id-type: auto
    banner: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8088